### ISSUE TITLE
Have `Exec` consume and return byte slices rather than strings

### ISSUE THREAD

**Issue by smulube** [thingful/zenroom-go#6]
I offer this just from my first tiny bit of usage of this zenroom library, so this might be bogus, but in that usage. I first read the input lua script (from go-bindata), but this could have been a file I guess, but in either case, what I actually get at that point is a byte slice. I then passed this byte slice into the `Exec` function after casting to a string (there were no other parameters in my case).

When the string that comes back from that function - I wanted to `json.Unmarshal` it into a struct for which I again had to cast the returned string to a byte slice before unmarshalling.

This just seemed like a lot of extra faffing about for the caller to have to do, and I'm just wondering if there could be an argument for changing the signature of `Exec` to be something like:

```go
func Exec(script, keys, data []byte) ([]byte, error) {
...
}
```

I haven't yet had a chance to use the keys or data parameters so really I don't know how I feel about them, but just thought I'd offer this as a discussion. I have no idea what the implications of this change would be internally.

I include the full text of my function for completeness:

```go
func NewKeyPair() (*KeyPair, error) {
	// read script from go-bindata asset
	script, err := lua.Asset("generatekeys.lua")
	if err != nil {
		return nil, errors.Wrap(err, "failed to read zenroom script")
	}

	// execute zenroom, passing in the script cast to a string
	keys, err := zenroom.Exec(string(script), "", "")
	if err != nil {
		return nil, errors.Wrap(err, "failed to execute zenroom script")
	}

	// unmarshal the returned data into a struct
	var keyPair KeyPair
	err = json.Unmarshal([]byte(keys), &keyPair)
	if err != nil {
		return nil, errors.Wrap(err, "failed to unmarshal zenroom output")
	}

	return &keyPair, nil
}
```

**Comment by jaromil** [comment]
Ahoy! I favor any effort to simplify usage and this is IMHO a good usecase.
The signature of the Zenroom function is
```c
int zenroom_exec(char *script, char *conf, char *keys,
                 char *data, int verbosity);
```
where a `char*` pointer is de-facto a byte array of 8bit chars. I'm not aware of any platform where the size would be different. There may be some considerations about UTF8 support here, but then I doubt the CODE section is the buffer, also I think they'd be premature to do.

So all in all I think you can consider the base C library as accepting byte arrays, while your issue may be related to the way the Go wrapper deals with `zenroom_exec`. Please  correct me if I'm wrong, I can certainly review the API signatures to improve the situation.

**Comment by smulube** [comment]
A big +1 for the usage of "Ahoy!" ;)

I'm interested in those other parameters to `zenroom_exec` - or specifically the `conf` parameter - what is that? Is that something that should also be exposed in the Go API?

**Comment by chespinoza** [comment]
Right, I was checking first and addressing this on PR #7 it should be an improvement.

**Comment by jaromil** [comment]
The `conf` parameter should be exposed too, yes. Right now is just a string that does nothing unless it contains "umm" which switches to a different memory manager. Later on it may do more things and perhaps even turn into a json with different configuration directives. It is a single string so that the binary API won't change when configuration changes.

**Comment by smulube** [comment]
@chespinoza - i think that maybe this should be a new issue, trying to think about the nicest way to add the `conf` param to our Go API.

**Comment by smulube** [comment]
Created issue #8
