### ISSUE TITLE
Expose conf param to `Exec` function as might be required for future functionality.

### ISSUE THREAD

**Issue by smulube** [thingful/zenroom-go#8]
Adding this issue as a placeholder as discussed in the thread for issue #7.

I always get slightly sweaty palms once the number of parameters to a function gets beyond 3 so I wonder if we should think about some alternative ways of passing in this extra parameter to the function.

As stated in the other thread, the actual signature of the underlying `zenroom_exec` function is:

```c
int zenroom_exec(char *script, char *conf, char *keys,
                 char *data, int verbosity);
```

which as you can see includes a `conf` parameter, as well as an `int` parameter which appears to control some verbosity of zenroom. This verbosity is less important, but the `conf` parameter would be desirable to expose via the Go API as it may have some future more significant role in configuring how zenroom is behaving.

Currently the Go API looks like this:

```go
func Exec(script, keys, data []byte) ([]byte, error) {
...
}
```

**Comment by smulube** [comment]
## Add separate `ExecWithConf` function

One option might be to expose a separate exec function that also takes this conf parameter:

```go
func ExecWithConf(script, keys, data, conf []byte) ([]byte, error) {
...
}
```

Clients are then free to call this version if they would like to specify a value for `conf`.

**Comment by smulube** [comment]
## Make conf variadic

One option might be to make the conf parameter optional by making it a variadic extra parameter to the normal Exec, so:

```go
func Exec(script, keys, data []byte, conf ...[]byte) ([]byte, error) {
...
}
```

This allows callers to optionally include a value for conf, without adding a new function to the public API.

**Comment by smulube** [comment]
## Pass parameters in a struct

An option might be to pass all parameters to the function inside single configuration object:

```go
type Params struct {
    Script    []byte
    Keys      []byte
    Data      []byte
    Conf      []byte
    Verbosity int
}

func Exec(params Params) ([]byte, error) {
...
}
```

I think this is nicer, just inasmuch as it it allows us to add both conf and even verbosity while keeping the function signature quite clean. Might there be an issue with default values, not sure.

**Comment by smulube** [comment]
## functional configuration

I did wonder about this, as I do like the variadic functional configuration approach for Go APIs, but I'm not sure if it is a good fit here. When I've used this before it has been in the context of being used to configure an instance of `Foo`, which we don't currently do here. 

The API might look something like:

```go
func Exec(script []byte, options ...Option) ([]byte, error) {
...
}
```

Where we say `script` is mandatory, but all other parameters are optional, and I'm not sure what the type of `Option` is here. 

However so how this might look to call:

```go
// omits the logic that initialises this script variable
var script []byte

// simple case of no extra config needed, just exec the script
output, _ := zenroom.Exec(script)

// add some data
output, _ = zenroom.Exec(script, zenroom.WithData(data))

// add conf and keys
output, _ = zenroom.Exec(script, zenroom.WithConf(conf), zenroom.WithKeys(keys))

// all options specified
output, _ = zenroom.Exec(script,
    zenroom.WithKeys(keys),
    zenroom.WithData(data),
    zenroom.WithConf(conf),
    zenroom.WithVerbosity(verbosity),
)
```

not sure how this would quite work however

**Comment by chespinoza** [comment]
I think @jaromil might have a more complete answer for this, in my view we don't need those parameters as configuration as far as I know is not being used right now and verbosity only affect the quantity of info messages that the zenroom VM send to STDOUT/STDERR.

**Comment by jaromil** [comment]
My preference would be to keep it same as zenroom_exec in C, this way the same documentation would apply also for the Go binding somehow.

But if you have strong feelings about passing a struct then I'm also fine. My second preference would be to use the most idiomatic and familiar approach to Go developers.
