### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by smulube** [thingful/zenroom-go#9]
If this is open source, we should have a license in here. I know there is a DECODE license, but not sure where it is, or if anyone is using it.

I'd propose adding Apache-2.0 as we've used for our other open source stuff just now, and we can change it should that be required.

**Comment by jaromil** [comment]
yes, Zenroom will be ultimately licensed Apache-2.0 keeping close to Milagro's licensing.

**Comment by chespinoza** [comment]
Added Apache 2.0 license - PR #10.
